management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

  #Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      default-zone : http://ec2-3-37-74-211.ap-northeast-2.compute.amazonaws.com:8761/eureka/
#
#zuul:
#  prefix:  /api
#  routes:
#    organizationservice: /organization/**
zuul:
  sensitive-headers: Cookie,Set-Cookie
