  #Setting logging levels
logging:
  file:
    path: /usr/local/pbzuul/logs

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : ${EUREKA_URI:http://58.149.234.98:5003/eureka}
